// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO0oHZTSv1TVUVKrQ6dU8QqIa44Nl3TK8',
    appId: '1:538649413044:web:ba1900ca342137397b9ee1',
    messagingSenderId: '538649413044',
    projectId: 'signinbookapp',
    authDomain: 'signinbookapp.firebaseapp.com',
    storageBucket: 'signinbookapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA9aQLEGmwnMkbIkz59AUxsGYWU00UfrI',
    appId: '1:538649413044:android:5e14df3e9b6f5bec7b9ee1',
    messagingSenderId: '538649413044',
    projectId: 'signinbookapp',
    storageBucket: 'signinbookapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdq4JRiptvFdttJeWhW0aXEKoylJnWBnY',
    appId: '1:538649413044:ios:9b76feb0acf91b907b9ee1',
    messagingSenderId: '538649413044',
    projectId: 'signinbookapp',
    storageBucket: 'signinbookapp.firebasestorage.app',
    iosBundleId: 'com.example.signint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdq4JRiptvFdttJeWhW0aXEKoylJnWBnY',
    appId: '1:538649413044:ios:9b76feb0acf91b907b9ee1',
    messagingSenderId: '538649413044',
    projectId: 'signinbookapp',
    storageBucket: 'signinbookapp.firebasestorage.app',
    iosBundleId: 'com.example.signint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO0oHZTSv1TVUVKrQ6dU8QqIa44Nl3TK8',
    appId: '1:538649413044:web:a14c35f2490662de7b9ee1',
    messagingSenderId: '538649413044',
    projectId: 'signinbookapp',
    authDomain: 'signinbookapp.firebaseapp.com',
    storageBucket: 'signinbookapp.firebasestorage.app',
  );
}
